// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygrandnrqqxovhgmguxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlncmFuZG5ycXF4b3ZoZ21ndXhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTA0NDUsImV4cCI6MjA2NzcyNjQ0NX0.iEA_VCiPEgOMBq0tAd1PkN7nS6EehpZ49kwOhC2o-YE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});